### ISSUE TITLE
Question about exam3

### ISSUE THREAD

**Issue by cghaocg** [cghaocg/data-engineer-exam#1]
Hello there, I have some question about exam3, I'd like to know is this task predict the "EventId" of next few time from the "test.csv" on exam2? Or do anomaly detection?

Thanks a lot.

**Comment by aaron-y-chen** [comment]
Hi, just do anomaly detection. Please try to give an approach to tell me which pattern are anomalies.

If you can give me the prediction of EventId and the model output distribution (maybe use softmax?), I think it will be very awesome! 😃

**Comment by cghaocg** [comment]
Hello, can I use other approach or just LSTM Model?

**Comment by aaron-y-chen** [comment]
Could you tell me your idea?

(Hint: you can see train.csv as the normal pattern set.)

**Comment by cghaocg** [comment]
I thought I could train with the data "train_need_aggregate.csv", but I'm not sure how to train with "train.csv".

**Comment by cghaocg** [comment]
I thought I could train the model from data "train_need_aggregate.csv", but I'm not sure how to train from the data "train.csv".

**Comment by aaron-y-chen** [comment]
You can use a sliding window to train, the idea like below:

<img width="428" alt="截圖 2020-06-11 下午3 46 17" src="https://user-images.githubusercontent.com/11390254/84359284-fc392a80-abfa-11ea-84d6-00fb82992780.png">

**Comment by cheyilin** [comment]
@cghaocg Please ping us when you finished the exam3, thanks!

**Comment by cghaocg** [comment]
No problem.

**Comment by cghaocg** [comment]
Hello @nailo2c , @CheyiLin , I finished the exam3. I still can't implement "train.py" with data "train.csv", so I implement with data "train_need_aggregate.csv", thanks.

**Comment by aaron-y-chen** [comment]
Got it, I'll check that later.

**Comment by aaron-y-chen** [comment]
The model can train as expected, well done.

**Comment by aaron-y-chen** [comment]
You can close this issue, thanks!

**Comment by cghaocg** [comment]
Got it, thanks!
