### ISSUE TITLE
improve exam1 algorithm from offline learning to online learning

### ISSUE THREAD

**Issue by nailo2c** [cghaocg/data-engineer-exam#2]
Hi, nice job for exam1, it looks like you get a great result from applying the *IsolationForest* algorithm.

However, if the data size is huge or data distribution change very fast, maybe the offline learning model would lose its performance.

Please try to improve *algorithm.py* to the online learning and do not modify my *detect* function in *detector.py*.

If have any question, please let me know on the comment, I will reply ASAP.

**Comment by aaron-y-chen** [comment]
Hi @cghaocg , I have seen your update for *algorithm.py*, it looks like you have used some package that not in *requirements.txt*. Could you update the *requirements.txt*?

**Comment by cghaocg** [comment]
Sure. If your "OS X >= 10.7" and have some problem with install package "mmh3", maybe you can reference this [stackoverflow](https://stackoverflow.com/questions/53792480/installing-mmh3-package-with-pip-on-conda-macos) and install manually.
