### ISSUE TITLE
reduce the code number and improve performance for exam 2

### ISSUE THREAD

**Issue by nailo2c** [cghaocg/data-engineer-exam#3]
Hi @cghaocg , it was very elegant to use the *.resample()* method to aggregate the file.

But there has a more efficient way to produce the result than using the *.sum()* method and for a loop.

Please check the [document](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) and improve the code. Ping me when you finished, thanks!

**Comment by cghaocg** [comment]
Hello @nailo2c , I finished exam2 and pushed it, thanks!

**Comment by aaron-y-chen** [comment]
@cghaocg , well done, the code performance has huge improve 😃
[Before] 641 ms ± 7.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) 
[After] 157 ms ± 4.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
