### ISSUE TITLE
exam3 should support epochs arguments

### ISSUE THREAD

**Issue by nailo2c** [cghaocg/data-engineer-exam#4]
Hi @cghaocg , please add *--train* args so that I can determine how many epochs should model trains.

**Comment by cghaocg** [comment]
Hello @nailo2c , I set the arg is _--epochs_ according the exam. Should I modify to _--train_? Thanks.

**Comment by aaron-y-chen** [comment]
Hi @cghaocg , sorry is my fault, I mean *--epochs* actually.

I see you hard-coding *epochs* in [this line](https://github.com/cghaocg/data-engineer-exam/blob/ff8bde538199d9aa8b11ebdec048f1db333d29f1/exam3/train.py#L63), so your *argparse* is not worked.

**Comment by cghaocg** [comment]
Hello @nailo2c , sorry is my fault, I had pushed it again.
